apiVersion: v1
kind: Service
metadata:
  name: devops-service
  annotations:
    cloud.google.com/backend-config: '{"default":"devops-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: devops-app
  ports:
    - port: 80
      targetPort: 8080
